config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    collection do
      post :confirm
      patch :confirm # confirm後のupdateに必要
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if params[:back]
      render :new
    else
      if @post.save
        redirect_to posts_path, notice: "Tweetしました！"
      else
        render :new
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: "Tweetを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path, notice:"Tweetを削除しました！"
    else
      render :index
    end
  end
  
  def confirm
    @post = Post.new(post_params)
    render :new if @post.invalid?
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appkadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <header>
      <h1 class="headline">
        <a> ʕ•ᴥ•ʔ </a><a> みんつぶ </a><a> ʕ•ᴥ•ʔ </a>
      </h1>
    </header>
    <footer>
      <p>~つぶやきを知ると世界が平和に~</p>
      <p>© 2015-2018 Copyright ANYA SPY FAM Corp.</p>
    </footer>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true ,url: confirm_posts_path ) do |form| %>
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2>入力内容にエラーがあります</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "Tweets一覧画面にもどる", posts_path %>

app/views/posts/confirm.html.erb
<h3>以下の内容で送信する</h3>

<%= form_with(model: @post, url: posts_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @post.content %></p>
  <%= form.submit  "送信する" %>

  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/posts/edit.html.erb
  <h2>Tweetを編集する</h2>

  <%= render 'form' %>

app/views/posts/index.html.erb
<h1>みんなのつぶやき</h1>

<p><%= notice %></p>

<div class="main_table">
  <table>
    <tr>
      <th>Tweets</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>

    <% @posts.each do |post| %>
      <tr>
        <td><%= post.content %></td>
        <td><%= link_to '詳細', post_path(post.id) %></td>
        <td><%= link_to "編集する", edit_post_path(post.id) %></td>
        <td><%= link_to '削除する', post_path(post.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
      </tr>
    <% end %>
  </table>
</div>

<%= link_to 'つぶやいてみる', new_post_path %>

app/views/posts/new.html.erb
  <h2>Tweetを作成する</h2>

  <%= render 'form' %>

app/views/posts/show.html.erb
<h1>Tweet詳細画面</h1>
<p>内容: <%= @post.content %></p>
<%= link_to "Tweets一覧画面にもどる", posts_path %>